void main() {
  try {
    dividir(
        10, 3); // Intentamos dividir por cero, lo que generar치 una excepci칩n.
  } catch (e) {
    print('Se ha producido una excepci칩n: $e');
  }
}

void dividir(int dividendo, int divisor) {
  if (divisor == 0) {
    throw Exception('No se puede dividir por cero.');
  }
  print('Resultado de la divisi칩n: ${dividendo / divisor}');
}
